# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('nicheng', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('haha', models.CharField(max_length=30)),
                ('haha2', models.CharField(max_length=30)),
            ],
        ),
    ]
