# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_auto_20170820_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='featureMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imageName', models.CharField(max_length=50)),
                ('textName', models.CharField(max_length=50)),
                ('feature', models.CharField(max_length=1024)),
            ],
        ),
    ]
